add_newline = false

[aws]
style = 'yellow'
format = 'on [$symbol($profile)(::$region) \[$duration\]]($style) '

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
disabled = true

[battery]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 0

[hostname]
ssh_only = false
style = "bold blue"

[kubernetes]
disabled = false
symbol = "⎈ "
style = 'cyan'
[kubernetes.context_aliases]
'.*jt(?P<var_cluster>[\w-]+)' = 'jt$var_cluster'

[line_break]
disabled = true

[status]
disabled = false

[terraform]
format = "via [$symbol$version]($style) "

[username]
format = "[$user]($style) at "
show_always = true

[gcloud]
disabled = true
